### ISSUE TITLE
az-switch fails with: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by mowtschan** [abij/az-account-switcher#1]
az-switch fails because some azure subscriptions are disabled:

``` 
$ az-switch 
Expecting value: line 1 column 1 (char 0)
```

```
$ az account list --output json

A few accounts are skipped as they don't have 'Enabled' state. Use '--all' to display them.
[
  {
    "cloudName": "AzureCloud",
...

```

Maybe a simple fix like:
```
az account list --output json --all
```
https://github.com/abij/az-account-switcher/blob/de411eb060d17ab38db87d629e339e03429e7096/az_account_switcher/az_account_switcher.py#L17

**Comment by abij** [comment]
thx for the feedback, going for a fix soon!

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: mowtschan ***@***.***>
Verzonden: Thursday, March 11, 2021 7:24:25 AM
Aan: abij/az-account-switcher ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [abij/az-account-switcher] az-switch fails with: Expecting value: line 1 column 1 (char 0) (#1)


az-switch fails because some azure subscriptions are disabled:

$ az-switch
Expecting value: line 1 column 1 (char 0)


$ az account list --output json

A few accounts are skipped as they don't have 'Enabled' state. Use '--all' to display them.
[
  {
    "cloudName": "AzureCloud",
...



Maybe a simple fix like:

az account list --output json --all


https://github.com/abij/az-account-switcher/blob/de411eb060d17ab38db87d629e339e03429e7096/az_account_switcher/az_account_switcher.py#L17

**Comment by abij** [comment]
Fixed with your suggestion and created a new version: https://github.com/abij/az-account-switcher/releases/tag/v0.0.6
`pip install -U az-account-switcher` solves the issue
